<?php
/**
 * Diamix_Correios Module
 */

/**
 * Product Quote
 * 
 * Contains the block for estimate quote on product page.
 * @version 1.0
 * @category Shipping
 * @package Diamix_Correios
 * @license GNU General Public License, version 3
 */
?>
<?php $showBox = Mage::helper('Diamix_Correios')->getConfigValue('estimate_quote_box');  // display estimate box if set to Yes ?>
<?php if (($this->getProduct()->getTypeId() != 'downloadable' && $this->getProduct()->getTypeId() != 'virtual') && $showBox == 1) : // display only for products that can be shipped ?>
<div id="estimateBox" class="estimate-box col-xs-12">
    <div class="widget">
        <div class="widget-header">
            <h2><?php echo $this->__('Estimate Shipping'); ?></h2>
        </div>
        <div class="widget-content">
            <form id="estimateQuote" class="form-inline">
                <input type="hidden" id="quoteUrl" name="quoteUrl" value="<?php echo $this->getUrl('diamix_correios/quote'); ?>" />
                <input type="hidden" id="productType" name="productType" value="<?php echo $this->getProduct()->getTypeId(); ?>" />
                <input type="hidden" id="currentProduct" name="currentProduct" value="<?php echo $this->getProduct()->getId(); ?>" />
                <div class="input-group">
                    <label for="postcode" class="sr-only"><?php echo $this->__('Postcode'); ?></label>
                    <input id="postcode" type="text" name="postcode" class="form-control input-text" placeholder="<?php echo $this->__('Postcode'); ?>" />
                </div>
                <div id="buttonQuote" class="input-group">
                    <button type="button" id="estimateQuoteSubmit" title="<?php echo $this->__('Quote'); ?>" class="button btn-quote" onclick="getQuote()">
                        <span>
                            <span><?php echo $this->__('Quote'); ?></span>
                        </span>
                    </button>
                </div>
            </form>
        </div>
        <div class="clear"></div>
    </div>
    <div class="widget quote-results-box" id="quoteResultsBox" style="display: none;">
    </div>
</div>
<?php endif; ?>